[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  GO_VERSION = "1.20"
  NODE_VERSION = "18"
  OPENAI_API_KEY = "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"
  PERPLEXITY_API_KEY = "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"
  NEXT_PUBLIC_CONVEX_URL = "https://accomplished-finch-529.convex.cloud"
  CONVEX_DEPLOYMENT = "dev:accomplished-finch-529"
  NEXT_PUBLIC_SUPABASE_URL = "https://pqmrlxuiqaenfhssduik.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxbXJseHVpcWFlbmZoc3NkdWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExOTE3MDMsImV4cCI6MjA1Njc2NzcwM30.e89qaWbGtxNz4lMPJeCg7rzPuOv6nvCN2lxl9jY_ApE"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxbXJseHVpcWFlbmZoc3NkdWlrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTE5MTcwMywiZXhwIjoyMDU2NzY3NzAzfQ._C8ohV-GIkn3lyvuf6dqXbORJs6pRLunFlFAgyR55yc"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 